
GET http://localhost:5104/controller
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTY3N2QxNC03NzVjLTQ3NWQtYWE3OS0zNjk4ZGRmNjVkMTYiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiI0MDk0OTM1OC1iYjAxLTRmYjMtYjA4MS0yNjJlNGVkNmYyZDQiLCJleHAiOjE3MzM2MTU2OTMsImlzcyI6Ikluc3VyYW5jZUNvbXBhbnkifQ.ngTVjoP__5tvvwdfVE1UyQgPEORCYEycqFVZkBDBItY