@host = http://localhost:5104

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Osta",
    "lastName": "Postrad",
    "email": "OstapPos@gmail.com",
    "password": "123456"

}



